#!/usr/bin/env python3
"""Validate dependency lock + docs inventory synchronization."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

_NAME_RE = re.compile(r"^\s*([A-Za-z0-9_.-]+)")


@dataclass(frozen=True)
class RequirementEntry:
    name: str
    normalized_name: str
    spec: str


def _normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _parse_requirements(path: Path) -> list[RequirementEntry]:
    entries: list[RequirementEntry] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith(("-r", "--", "-c", "-e")):
            continue
        line = line.split("#", 1)[0].strip()
        if not line:
            continue

        markerless = line.split(";", 1)[0].strip()
        match = _NAME_RE.match(markerless)
        if not match:
            continue
        name = match.group(1)
        entries.append(
            RequirementEntry(
                name=name,
                normalized_name=_normalize_name(name),
                spec=line,
            )
        )
    return entries


def _parse_lock_names(path: Path) -> set[str]:
    names: set[str] = set()
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith(("-r", "--", "-c", "-e")):
            continue
        markerless = line.split(";", 1)[0].strip()
        match = _NAME_RE.match(markerless)
        if not match:
            continue
        names.add(_normalize_name(match.group(1)))
    return names


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _render_inventory(
    requirements_path: Path,
    dev_requirements_path: Path,
    lock_path: Path,
    runtime_entries: list[RequirementEntry],
    dev_entries: list[RequirementEntry],
    lock_count: int,
    covered_count: int,
    total_direct_count: int,
) -> str:
    lines: list[str] = []
    lines.append("# Dependency Inventory")
    lines.append("")
    lines.append(
        "This file is generated by "
        "`python3 scripts/check_dependency_sync.py --requirements requirements.txt --dev-requirements requirements-dev.txt --lock requirements.lock --doc docs/reference/dependencies.md --write-doc`."
    )
    lines.append("Do not edit manually.")
    lines.append("")
    lines.append("## Source Manifests")
    lines.append(f"- `{requirements_path.as_posix()}`")
    lines.append(f"- `{dev_requirements_path.as_posix()}`")
    lines.append(f"- `{lock_path.as_posix()}`")
    lines.append("")
    lines.append(f"## Runtime Requirements (`{requirements_path.name}`)")
    lines.append("| Package | Spec |")
    lines.append("| --- | --- |")
    for entry in runtime_entries:
        lines.append(f"| `{entry.name}` | `{entry.spec}` |")
    lines.append("")
    lines.append(f"## Development Requirements (`{dev_requirements_path.name}`)")
    lines.append("| Package | Spec |")
    lines.append("| --- | --- |")
    for entry in dev_entries:
        lines.append(f"| `{entry.name}` | `{entry.spec}` |")
    lines.append("")
    lines.append("## Lock Coverage")
    lines.append(
        f"- Direct requirements covered by lockfile: `{covered_count}/{total_direct_count}`"
    )
    lines.append(f"- Total locked package entries: `{lock_count}`")
    lines.append("")
    lines.append("## Lockfile Fingerprint")
    lines.append(f"- `sha256({lock_path.name})`: `{_sha256(lock_path)}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check dependency lock/docs synchronization."
    )
    parser.add_argument("--requirements", required=True)
    parser.add_argument("--dev-requirements", required=True)
    parser.add_argument("--lock", required=True)
    parser.add_argument("--doc", required=True)
    parser.add_argument(
        "--write-doc",
        action="store_true",
        help="Write rendered inventory to --doc instead of check-only mode.",
    )
    args = parser.parse_args()

    requirements_path = Path(args.requirements)
    dev_requirements_path = Path(args.dev_requirements)
    lock_path = Path(args.lock)
    doc_path = Path(args.doc)

    for path in (requirements_path, dev_requirements_path, lock_path):
        if not path.exists():
            print(f"Missing required file: {path}", file=sys.stderr)
            return 1

    runtime_entries = _parse_requirements(requirements_path)
    dev_entries = _parse_requirements(dev_requirements_path)
    direct_entries = runtime_entries + dev_entries
    direct_names = {entry.normalized_name for entry in direct_entries}

    lock_names = _parse_lock_names(lock_path)
    missing_in_lock = sorted(direct_names - lock_names)
    if missing_in_lock:
        print("Lockfile is missing direct requirements:", file=sys.stderr)
        for name in missing_in_lock:
            print(f"- {name}", file=sys.stderr)
        return 1

    rendered = _render_inventory(
        requirements_path=requirements_path,
        dev_requirements_path=dev_requirements_path,
        lock_path=lock_path,
        runtime_entries=runtime_entries,
        dev_entries=dev_entries,
        lock_count=len(lock_names),
        covered_count=len(direct_names),
        total_direct_count=len(direct_names),
    )

    if args.write_doc:
        doc_path.write_text(rendered, encoding="utf-8")
        return 0

    if not doc_path.exists():
        print(f"Dependency inventory file is missing: {doc_path}", file=sys.stderr)
        return 1

    current = doc_path.read_text(encoding="utf-8")
    if current != rendered:
        print(
            "Dependency inventory drift detected. "
            "Run `python3 scripts/check_dependency_sync.py "
            "--requirements requirements.txt --dev-requirements requirements-dev.txt "
            "--lock requirements.lock --doc docs/reference/dependencies.md --write-doc`.",
            file=sys.stderr,
        )
        return 1

    print(
        "Dependency lock and docs inventory are synchronized "
        f"({len(direct_names)} direct requirements, {len(lock_names)} locked packages)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
